### PR TITLE
Optionally resolve wrapper index to single-platform manifest based on `com.apple.containerization.index.indirect` annotation

### LINKED ISSUE #212: [Bug]: `index.digest` not consistent after pulls
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

Pull the following image and dump its digest with `jq`. You'll get different results each time.

```
$ image="gcr.io/k8s-staging-cri-tools/test-image-digest@sha256:9700f9a2f5bf2c45f2f605a0bd3bce7cf37420ec9d3ed50ac2758413308766bf"
$ container image pull $image
$ container image inspect $image | jq '.[].index.digest'
``` 

### Current behavior

The digest is changed by every pull action:

```
$ image="gcr.io/k8s-staging-cri-tools/test-image-digest@sha256:9700f9a2f5bf2c45f2f605a0bd3bce7cf37420ec9d3ed50ac2758413308766bf"
$ container image pull $image
$ container image inspect $image | jq '.[].index.digest'
"sha256:0570a026b6348a1b02bae16156ccfc945aff10e0c322507e83e7ea962988e56c"
$ container image inspect $image | jq '.[].index.digest'
"sha256:0570a026b6348a1b02bae16156ccfc945aff10e0c322507e83e7ea962988e56c"
$ container image pull $image
$ container image inspect $image | jq '.[].index.digest'
"sha256:7fb9571b54af27a9f25e08ebe305aeba2c5e87d0c11f8fbe4411945ef8fec186"
```

### Expected Behavior

The digest should always be `sha256:9700f9a2f5bf2c45f2f605a0bd3bce7cf37420ec9d3ed50ac2758413308766bf`.

### Environment

```markdown
- OS: macOS 15.5 (24F74)
- Xcode: Version 26.0 beta (17A5241e)
- Container: container CLI version 0.1.0 (build: release, commit: 0fd8692)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by stevapple**
This PR:
- adds a `package func resolved()` on `ClientImage` that makes use of the new `com.apple.containerization.index.indirect` annotation to identify and resolve wrapper indices created by Containerization;
- replace the digest displayed in `container image list` with the one of the resolved manifest;
- use the resolved manifest for `container image inspect` if the index is a wrapper.

Fixes #212, as shown with the following local result:
image

### CODE REVIEW

**Comment by stevapple** [comment]
@adityaramani may you review the pull if you have time?

File: Sources/ContainerClient/Core/ClientImage.swift [hunk 1]
```diff
@@ -69,6 +69,16 @@ public struct ClientImage: Sendable {
         }
         return try content.decode()
     }
+
+    /// Returns the resolved OCI descriptor for the image.
+    package func resolved() async throws -> Descriptor {
+        let index = try await self.index()
+        if index.annotations?[AnnotationKeys.containerizationIndexIndirect] == "true" {
+            return index.manifests.first!
```
Comment (adityaramani) [inline Sources/ContainerClient/Core/ClientImage.swift]: This should work all the time - but just in case somehow something went wrong I think we should check for a nil value here

Maybe we can do something like this. What do you think?
```
guard index.annotations?[AnnotationKeys.containerizationIndexIndirect] == nil else {
   return self.descriptor
}
guard let manifest = index.manifests.first else {
   throw ContainerizationError(.internalError, message: "Malformed image .... ")
}
return manifest
```
