### PR TITLE
Prevent removal of network with container references.

### LINKED ISSUE #392: [Bug]: Don't allow `network rm` if any containers reference the network.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

Currently `container network rm` guards against the removal of a network that is in use by running containers.

It should instead ensure that no containers reference the network.

### Current behavior

```console
% container network create foo
foo
% container create -it --rm --network foo --name web python:slim
web                              
% container network rm foo
foo
/Users/john/Documents/projects/jglogan/container main us-west-2e % container start web
Error: interrupted: "interrupted: "XPC connection error: Connection invalid"
Ensure container system service has been started with `container system start`."
```

### Expected behavior

`container network rm foo` should fail, listing the containers that need to be removed first.

### Environment

```markdown
- OS: Tahoe preview
- Xcode: 26 beta
- Container: main
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jglogan**
- Closes #392.

### CODE REVIEW

File: Sources/APIServer/Networks/NetworksService.swift [hunk 1]
```diff
@@ -161,28 +172,61 @@ actor NetworksService {
...
 
-        do {
-            try await store.delete(id)
-        } catch {
-            throw ContainerizationError(.notFound, message: error.localizedDescription)
+            // disable the allocator so nothing else can attach
+            // TODO: remove this from the network helper later, not necesssary now that withContainerList is here
+            let client = NetworkClient(id: id)
+            guard try await client.disableAllocator() else {
+                throw ContainerizationError(.invalidState, message: "cannot delete subnet \(id) with active containers")
```
Comment (realrajaryan) [inline Sources/APIServer/Networks/NetworksService.swift]: nit: would this be a better error message?
```suggestion
                throw ContainerizationError(.invalidState, message: "cannot delete subnet \(id) - network allocator could not be disabled")
```

**Review by realrajaryan — APPROVED** [review]

**Review by realrajaryan — APPROVED** [review]
