### PR TITLE
fix: extract hostname from FQDN (#1011)

### LINKED ISSUE #1011: [Bug]: Hostname should not be a FQDN if the container name is.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

The hostname for a container with ID `foo.test` should be `foo`, not `foo.test`.

### Current behavior

```console
% container run --name foo.test -it --rm alpine hostname
foo.test
```

### Expected behavior

```console
% container run --name foo.test -it --rm alpine hostname
foo
```

### Environment

```markdown
- OS: 26
- Xcode: 26
- Container: main
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iko1**
## Type of Change
- [x] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Motivation and Context
Set  the container hostname to the first DNS label derived from the container id, strip everything after the first dot
Fixes #1011 

## Testing
- [x] Tested locally
- [ ] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

File: Sources/ContainerClient/Utility.swift [hunk 1]
```diff
@@ -368,4 +368,12 @@ public struct Utility {
 
         return volume
     }
+
+    public static func defaultHostname(containerId: String) -> String {
```
Comment (jglogan) [inline Sources/ContainerClient/Utility.swift]: Thanks for taking this one on!

nit: why is it `defaultHostname`, could it just be `hostname(containerId:)`?

Could you add a CLI test for this as well?

**Review by jglogan — CHANGES_REQUESTED** [review]

**Comment by jglogan** [comment]
@iko1 Please rebase onto the latest main as ContainerClient is gone, updating your imports as needed:

- ContainerAPIClient has the actual client code
- ContainerResource has the core types
- ContainerSandboxServiceClient has the sandbox client code (unlikely you're using this though)

**Comment by iko1** [comment]
> @iko1 there's a build error due to the client reorg. Since SandboxService is the only thing that uses `hostname`, perhaps for now you could just inline something like this into SandboxService L834?
> 
> ```swift
> czConfig.hostname = containerId.split(separator: ".", maxSplits: 1, omittingEmptySubsequences: true)
>     .first
>     .map { String($0) } ?? containerId
> ```

Done

**Comment by jglogan** [comment]
@iko1 Looks like some test compile errors now:

```
/Users/runner/actions-runner/_work/container/container/Tests/CLITests/Subcommands/Containers/TestCLICreate.swift:113:29: error: value of type 'CLITest.inspectOutput' has no member 'hostname'
111 |             let inspectResp = try inspectContainer(name)
112 |             #expect(
4 | }
5 | 

/Users/runner/actions-runner/_work/container/container/Tests/CLITests/Subcommands/Containers/TestCLICreate.swift:114:117: error: value of type 'CLITest.inspectOutput' has no member 'hostname'
112 |             #expect(
113 |                 inspectResp.hostname == expectedHostname,
114 |                 "expected hostname to be extracted as '\(expectedHostname)' from FQDN '\(name)', got '\(inspectResp.hostname)'"
    |                                                                                                                     `- error: value of type 'CLITest.inspectOutput' has no member 'hostname'
115 |             )
116 |         }
[210/222] Compiling CLITests TestCLICreate.swift
/Users/runner/actions-runner/_work/container/container/Tests/CLITests/Subcommands/Containers/TestCLICreate.swift:113:29: error: value of type 'CLITest.inspectOutput' has no member 'hostname'
111 |             let inspectResp = try inspectContainer(name)
112 |             #expect(
113 |                 inspectResp.hostname == expectedHostname,
    |                             `- error: value of type 'CLITest.inspectOutput' has no member 'hostname'
114 |                 "expected hostname to be extracted as '\(expectedHostname)' from FQDN '\(name)', got '\(inspectResp.hostname)'"
115 |             )

/Users/runner/actions-runner/_work/container/container/Tests/CLITests/Subcommands/Containers/TestCLICreate.swift:114:104: error: generic parameter 'some StringProtocol' could not be inferred
112 |             #expect(
113 |                 inspectResp.hostname == expectedHostname,
114 |                 "expected hostname to be extracted as '\(expectedHostname)' from FQDN '\(name)', got '\(inspectResp.hostname)'"
    |                                                                                                        `- error: generic parameter 'some StringProtocol' could not be inferred
115 |             )
116 |         }

Testing.Comment.StringInterpolation.appendInterpolation:3:33: note: in call to function 'appendInterpolation'
1 | struct Comment {
2 |   struct StringInterpolation {
3 | @inlinable public mutating func appendInterpolation(_ value: (some StringProtocol)?)  }
  |                                 `- note: in call to function 'appendInterpolation'
4 | }
5 | 

/Users/runner/actions-runner/_work/container/container/Tests/CLITests/Subcommands/Containers/TestCLICreate.swift:114:117: error: value of type 'CLITest.inspectOutput' has no member 'hostname'
112 |             #expect(
113 |                 inspectResp.hostname == expectedHostname,
114 |                 "expected hostname to be extracted as '\(expectedHostname)' from FQDN '\(name)', got '\(inspectResp.hostname)'"
    |                                                                                                                     `- error: value of type 'CLITest.inspectOutput' has no member 'hostname'
115 |             )
116 |         }
```

**Comment by iko1** [comment]
@jglogan  Fixed now. Test compile errors resolved.

**Comment by jglogan** [comment]
Everything looks good but the new test fails the CI build. I pulled your branch and it works fine for me locally, so I'm going to try it out on a system that's more like the CI runner to see if I can get more info about the failure.
