### PR TITLE
Fix CI integration test coldstart issues.

### LINKED ISSUE #507: [Request]: Consistent, useful behavior for `--debug`.
### Feature or enhancement request details

Tasks:

- [ ] `--debug` is available every that it makes sense.
- [ ] The global flags to which `--debug` belongs appear in consistent order relative to other options across all subcommands.
- [ ] Where `--debug` does appear, it provides clear and actionable output. If the debug output does appears elsewhere than the CLI output (e.g. OS logs), the CLI informs the user where the debug output can be found.
- [ ] If debug is not present and the `CONTAINER_DEBUG` environment variable is truthy, debug is enabled.
- [ ] `CONTAINER_DEBUG` included in help text for debug everywhere (or consider removing it everywhere if we switch to using env variables instead of user defaults for settings). At present all commands seem to display it except `system start`.

Right now these leaf commands do not have `--debug`:

- build
- registry login
- default unset
- default inspect
- volume [*]
- builder [*]
- system dns [*]
- system stop
- system status
- system kernel set
- help

Perhaps we can look at #360 as well while attending to this one.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1185: [Bug]: Local `vminit:latest` install doesn't honor APP_ROOT.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

While validating apple/containerization#379 I wanted to run container integration tests using an alternate APP_ROOT. I found that this doesn't work as expected because the locally build `vminit:latest` was being installed into the standard app root under `Application Support` regardless of the value of APP_ROOT.

With local modifications in `path/to/containerization`:

```bash
swift package edit containerization --path path/to/containerization
container system property set image.init vminit:latest
make APP_ROOT=test-data all test integration
```

### Current behavior

- `make all` installs locally built vminit image under `~/Library/Application Support/com.apple.containerization`.
- `make integration` tests fail due missing vminitd.

### Expected behavior

- `make all` installs locally built vminit image under `test-data`.
- `make integration` tests pass.

### Environment

```markdown
- OS: 26
- Xcode: 26
- Container: main + local changes for swift-grpc-2
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1206: [chore]: Fix CLINetwork tests.
### Feature or enhancement request details

CLI network tests were serialized as a workaround for intermittent failures. They are now disabled entirely so we can unblock CI and merge some PRs.

While troubleshooting #1205 I saw that when a network is created on the CI systems, there is an 8 sec or longer delay between registration of the launch plist and execution of the network helper.

If this is occurring for network tests, it's reasonably likely that this is the cause for failures there.

Once we have log collection merged, we can reenable and parallelize the tests, and determine what code and/or tests require fixing.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jglogan**
- Closes #1206.
- Closes #1185.
- Closes #507.
- Addresses existing log messages for #642.
- Nondeterministic CI errors are resulting from very slow launch times for the first runtime helper, which causes ContainersService to be locked for longer than our 20 sec timeout. Bumping the timeout to 60 seconds addresses this case for now.
- Since many log messages needed to be changed to troubleshoot the issue, updated all log messages to use structured logging, and implemented consistent entry/exit logging for all service operations.
- Added logging for ContainerService lock acquisition to help with finding root cause for the slow service startup.
- Plumbed the `--debug` flag on both `container system start` and `container system logs` so that the flag is actually useful.
- Updated the `install-init.sh` script so that can install in a custom app root directory.

### CODE REVIEW

File: scripts/install-init.sh [hunk 1]
```diff
@@ -13,10 +13,53 @@
...
+    case $1 in
+        -a|--app-root)
+            if [[ -z "$2" || "$2" == -* ]]; then
+                echo "Option $1 requires an argument." >&2
+                usage
+            fi
+            START_ARGS+=(--app-root "$2")
+            shift 2
+            ;;
+        -l|--log-root)
```
Comment (jglogan) [inline scripts/install-init.sh:43]: Nothing uses this yet, but it will be used when the CI log collection PR posts.

File: scripts/install-init.sh [hunk 2]
```diff
@@ -13,10 +13,53 @@
...
+        *)
+            echo "Invalid option: $1" >&2
+            usage
+            ;;
+    esac
+done
+
 SWIFT="/usr/bin/swift"
 IMAGE_NAME="vminit:latest"
-DEST_DIR="${1:-$(git rev-parse --show-toplevel)/bin}"
```
Comment (jglogan) [inline scripts/install-init.sh:18]: This is dead code, removed it

File: scripts/install-init.sh [hunk 3]
```diff
@@ -28,8 +71,12 @@ if [ "${CONTAINERIZATION_VERSION}" == "unspecified" ] ; then
 	echo "Creating InitImage"
 	make -C ${CONTAINERIZATION_PATH} init
 	${CONTAINERIZATION_PATH}/bin/cctl images save -o /tmp/init.tar ${IMAGE_NAME}
+
 	# Sleep because commands after stop and start are racy.
-	bin/container system stop && sleep 3 && bin/container system start && sleep 3
+	bin/container system stop
+    sleep 3
+	bin/container --debug system start "${START_ARGS[@]}"
```
Comment (jglogan) [inline scripts/install-init.sh:78]: This is the essential change to the script

File: Sources/ContainerCommands/System/SystemLogs.swift [hunk 4]
```diff
@@ -58,7 +58,7 @@ extension Application {
             do {
                 var args = ["log"]
                 args.append(self.follow ? "stream" : "show")
-                args.append(contentsOf: ["--info", "--debug"])
+                args.append(contentsOf: ["--info", logOptions.debug ? "--debug" : nil].compactMap { $0 })
```
Comment (jglogan) [inline Sources/ContainerCommands/System/SystemLogs.swift:61]: Now we only pass debug into `log stream` for `container --debug system logs`.

File: Sources/ContainerCommands/System/SystemStart.swift [hunk 5]
```diff
@@ -48,9 +49,15 @@ extension Application {
...
-        var timeout: Double = 10.0
+            help: "Number of seconds to wait for API service to become responsive",
+            transform: {
+                guard let timeoutSeconds = Double($0) else {
+                    throw ValidationError("Invalid timeout value: \($0)")
+                }
+                return .seconds(timeoutSeconds)
+            }
+        )
+        var timeout: Duration = XPCClient.xpcRegistrationTimeout
```
Comment (jglogan) [inline Sources/ContainerCommands/System/SystemStart.swift:60]: Key point here is that we use the common timeout value now.

File: Sources/ContainerPlugin/PluginLoader.swift [hunk 6]
```diff
@@ -223,9 +224,10 @@ extension PluginLoader {
         env[ApplicationRoot.environmentName] = appRoot.path(percentEncoded: false)
         env[InstallRoot.environmentName] = installRoot.path(percentEncoded: false)
 
+        let processedArgs = (args ?? ["start"]) + (debug ? ["--debug"] : [])
```
Comment (jglogan) [inline Sources/ContainerPlugin/PluginLoader.swift:227]: This is the main change, adds `--debug` to the plugin startup as necessary.

The implication is that all plugins need to implement a `start` subcommand that accepts a `--debug` flag.

File: Sources/ContainerXPC/XPCClient.swift [hunk 7]
```diff
@@ -19,6 +19,13 @@ import ContainerizationError
 import Foundation
 
 public final class XPCClient: Sendable {
+    /// The maximum amount of time to wait for a request to a recently
+    /// registered XPC service. Once a service has launched, XPC
+    /// requests only have milliseconds of overhead, but in some instances,
+    /// macOS can take 5 seconds (or considerably longer) to launch a
+    /// service after it has been registered.
+    public static let xpcRegistrationTimeout: Duration = .seconds(60)
```
Comment (jglogan) [inline Sources/ContainerXPC/XPCClient.swift:27]: Our common timeout value, chosen to work with our slow service startup in CI.

File: Sources/Helpers/APIServer/APIServer+Start.swift [hunk 8]
```diff
@@ -46,22 +46,22 @@ extension APIServer {
         func run() async throws {
             let commandName = Self.configuration.commandName ?? "container-apiserver"
             let log = APIServer.setupLogger(debug: debug)
-            log.info("starting \(commandName)")
+            log.info("starting helper", metadata: ["name": "\(commandName)"])
```
Comment (jglogan) [inline Sources/Helpers/APIServer/APIServer+Start.swift:49]: This pattern is used for startup/shutdown for all services.

File: Sources/Helpers/APIServer/APIServer+Start.swift [hunk 9]
```diff
@@ -46,22 +46,22 @@ extension APIServer {
...
+                log.info("stopping helper", metadata: ["name": "\(commandName)"])
             }
 
             do {
                 log.info("configuring XPC server")
                 var routes = [XPCRoute: XPCServer.RouteHandler]()
                 let pluginLoader = try initializePluginLoader(log: log)
                 try await initializePlugins(pluginLoader: pluginLoader, log: log, routes: &routes)
-                let containersService = try initializeContainerService(
+                let containersService = try initializeContainersService(
```
Comment (jglogan) [inline Sources/Helpers/APIServer/APIServer+Start.swift:59]: Just some name nitpickery for "containers service" and "networks service".

File: Sources/Helpers/APIServer/APIServer+Start.swift [hunk 10]
```diff
@@ -246,25 +247,25 @@ extension APIServer {
...
+            log.info("initializing networks service")
 
             let resourceRoot = appRoot.appendingPathComponent("networks")
             let service = try await NetworksService(
                 pluginLoader: pluginLoader,
                 resourceRoot: resourceRoot,
                 containersService: containersService,
-                log: log
+                log: log,
+                debugHelpers: debug
```
Comment (jglogan) [inline Sources/Helpers/APIServer/APIServer+Start.swift:268]: Propagate debug settings from API server to any network helpers we create.

File: Sources/Helpers/APIServer/APIServer+Start.swift [hunk 11]
```diff
@@ -222,13 +222,14 @@ extension APIServer {
...
-            log.info("initializing container service")
+        private func initializeContainersService(pluginLoader: PluginLoader, log: Logger, routes: inout [XPCRoute: XPCServer.RouteHandler]) throws -> ContainersService {
+            log.info("initializing containers service")
 
             let service = try ContainersService(
                 appRoot: appRoot,
                 pluginLoader: pluginLoader,
-                log: log
+                log: log,
+                debugHelpers: debug
```
Comment (jglogan) [inline Sources/Helpers/APIServer/APIServer+Start.swift:232]: Propagate debug settings from API server to any runtime helpers we create.

File: Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift [hunk 12]
```diff
@@ -52,24 +50,32 @@ public actor ContainersService {
...
+    public init(
+        appRoot: URL,
+        pluginLoader: PluginLoader,
+        log: Logger,
+        debugHelpers: Bool = false
+    ) throws {
         let containerRoot = appRoot.appendingPathComponent("containers")
         try FileManager.default.createDirectory(at: containerRoot, withIntermediateDirectories: true)
         self.exitMonitor = ExitMonitor(log: log)
+        self.lock = AsyncLock(log: log)
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift:74]: Set up debug logging for lock acquisition/release

File: Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift [hunk 13]
```diff
@@ -111,15 +117,28 @@ public actor ContainersService {
...
+                log.warning("failed to load container", metadata: ["path": "\(dir.path)", "error": "\(error)"])
             }
         }
         return results
     }
 
     /// List containers matching the given filters.
     public func list(filters: ContainerListFilters = .all) async throws -> [ContainerSnapshot] {
-        self.log.debug("\(#function)")
+        log.debug(
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift:128]: This is the pattern we use everywhere for entry/exit on our service operations.

- All information on entry metadata.
- Only identifying information on exit metadata.
- `debug` level, except `trace` for potentially busy calls like `resize`.

File: Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift [hunk 14]
```diff
@@ -148,8 +167,11 @@ public actor ContainersService {
 
     /// Execute an operation with the current container list while maintaining atomicity
     /// This prevents race conditions where containers are created during the operation
-    public func withContainerList<T: Sendable>(_ operation: @Sendable @escaping ([ContainerSnapshot]) async throws -> T) async throws -> T {
-        try await lock.withLock { context in
+    public func withContainerList<T: Sendable>(
+        logMetadata: Logger.Metadata? = nil,
+        _ operation: @Sendable @escaping ([ContainerSnapshot]) async throws -> T
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift:172]: Allows us to trace locks from callers in other services using `withContainerList(logMetadata:) { ... }`

File: Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift [hunk 15]
```diff
@@ -158,7 +180,7 @@ public actor ContainersService {
     /// Calculate disk usage for containers
     /// - Returns: Tuple of (total count, active count, total size, reclaimable size)
     public func calculateDiskUsage() async -> (Int, Int, UInt64, UInt64) {
-        await lock.withLock { _ in
+        await lock.withLock(logMetadata: ["acquirer": "\(#function)"]) { _ in
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift:183]: Our pattern for tracking ContainersService lock usage.

File: Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift [hunk 16]
```diff
@@ -751,14 +1030,15 @@ public actor ContainersService {
...
+        path: URL,
+        debug: Bool
     ) throws {
         let args = [
             "start",
             "--root", path.path,
             "--uuid", configuration.id,
-            "--debug",
-        ]
+            debug ? "--debug" : nil,
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift:1040]: Propagate debug flag from API service to runtime helper.

File: Sources/Services/ContainerAPIService/Server/Networks/NetworksService.swift [hunk 17]
```diff
@@ -369,6 +408,9 @@ public actor NetworksService {
             "--mode",
             configuration.mode.rawValue,
         ]
+        if debugHelpers {
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Server/Networks/NetworksService.swift:411]: Propagate debug flag from API server to network helpers.

File: Tests/CLITests/Subcommands/Networks/TestCLINetwork.swift [hunk 18]
```diff
@@ -22,7 +22,6 @@ import ContainerizationOS
 import Foundation
 import Testing
 
-@Suite(.serialized)
```
Comment (jglogan) [inline Tests/CLITests/Subcommands/Networks/TestCLINetwork.swift:25]: Turn these tests back on and run them in parallel again.

File: Makefile [hunk 19]
```diff
@@ -33,10 +33,9 @@ DSYM_PATH := bin/$(BUILD_CONFIGURATION)/bundle/container-dSYM.zip
 CODESIGN_OPTS ?= --force --sign - --timestamp=none
 
 # Conditionally use a temporary data directory for integration tests
-ifeq ($(strip $(APP_ROOT)),)
```
Comment (jglogan) [inline Makefile:36]: Don't do this anymore since we'll want to add other options (--log-root) soon. Make it so we can accumulate startup options.

File: Sources/ContainerCommands/Network/NetworkPrune.swift [hunk 20]
```diff
@@ -55,7 +55,7 @@ extension Application.NetworkCommand {
                     // Note: This failure may occur due to a race condition between the network/
                     // container collection above and a container run command that attaches to a
                     // network listed in the networksToPrune collection.
-                    log.error("Failed to prune network \(network.id): \(error)")
+                    log.error("failed to prune network", metadata: ["id": "\(network.id)", "error": "\(error)"])
```
Comment (ajemory) [inline Sources/ContainerCommands/Network/NetworkPrune.swift:58]:
```suggestion
                    log.error(
                        "failed to prune network", 
                        metadata: [
                            "id": "\(network.id)", 
                            "error": "\(error)",
                        ])
```

File: Sources/Helpers/Images/ImagesHelper.swift [hunk 21]
```diff
@@ -76,7 +77,7 @@ extension ImagesHelper {
                 log.info("starting XPC server")
                 try await xpc.listen()
             } catch {
-                log.error("\(commandName) failed", metadata: ["error": "\(error)"])
+                log.error("helper failed", metadata: ["name": "\(commandName)", "error": "\(error)"])
```
Comment (ajemory) [inline Sources/Helpers/Images/ImagesHelper.swift:80]:
```suggestion
                log.error(
                    "helper failed",
                    metadata: [
                        "name": "\(commandName)", 
                        "error": "\(error)",
                    ])
```

File: Sources/Helpers/NetworkVmnet/NetworkVmnetHelper+Start.swift [hunk 22]
```diff
@@ -110,7 +110,7 @@ extension NetworkVmnetHelper {
                 log.info("starting XPC server")
                 try await xpc.listen()
             } catch {
-                log.error("\(commandName) failed", metadata: ["error": "\(error)"])
+                log.error("helper failed", metadata: ["name": "\(commandName)", "error": "\(error)"])
```
Comment (ajemory) [inline Sources/Helpers/NetworkVmnet/NetworkVmnetHelper+Start.swift:113]:
```suggestion
                log.error(
                    "helper failed", 
                    metadata: [
                        "name": "\(commandName)", 
                        "error": "\(error)",
                    ])
```

File: Sources/Helpers/RuntimeLinux/RuntimeLinuxHelper+Start.swift [hunk 23]
```diff
@@ -118,7 +117,7 @@ extension RuntimeLinuxHelper {
                     _ = try await group.next()
                 }
             } catch {
-                log.error("\(commandName) failed", metadata: ["error": "\(error)"])
+                log.error("helper failed", metadata: ["name": "\(commandName)", "error": "\(error)"])
```
Comment (ajemory) [inline Sources/Helpers/RuntimeLinux/RuntimeLinuxHelper+Start.swift:120]:
```suggestion
                log.error(
                    "helper failed", 
                    metadata: [
                        "name": "\(commandName)", 
                        "error": "\(error)",
                    ])
```

File: Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift [hunk 24]
```diff
@@ -111,15 +117,28 @@ public actor ContainersService {
                 }
             } catch {
                 try? FileManager.default.removeItem(at: dir)
-                log.warning("failed to load container at \(dir.path): \(error)")
+                log.warning("failed to load container", metadata: ["path": "\(dir.path)", "error": "\(error)"])
```
Comment (ajemory) [inline Sources/Services/ContainerAPIService/Server/Containers/ContainersService.swift:120]:
```suggestion
                log.warning(
                    "failed to load container", 
                    metadata: [
                        "path": "\(dir.path)", 
                        "error": "\(error)",
                    ])
```

File: Sources/ContainerCommands/Network/NetworkPrune.swift (hunk 20 above)
Comment (jglogan) [reply Sources/ContainerCommands/Network/NetworkPrune.swift:58]: This is reasonable. Let me do it in the follow-up (log collection PR) so we can start unblocking the PR backlog.
