### PR TITLE
Fix container auto-delete on rapid stop/start

### LINKED ISSUE #833: [Bug]: Container auto deletes when we stop a container and start the same container within few milliseconds.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

Please watch the video:

https://github.com/user-attachments/assets/4654ec6d-8a72-4733-b960-05ca650753c7

### Current behavior

- Start a container 
```sh
container start redis
```
- Stop the container 
```sh
container stop redis
```
- Start same container within a second
```sh
container start redis
```
Here you will get `Error: internalError: "failed to bootstrap container" (cause: "internalError: "failed to bootstrap container redis (cause: "invalidState: "container expected to be in created state, got: shuttingDown"")"")`
And it automatically removes the container from the system.

### Expected behavior

- Start a container 
```sh
container start redis
```
- Stop the container 
```sh
container stop redis
```
- Start same container within a second
```sh
container start redis
```

with no errors or safe fallback [Last version I used was 0.4.1, and it works fine].

### Environment

```markdown
- OS: macOS 26.0.1 (25A362)
- Xcode: Version 26.0 (17A5276g)
- Container: 0.6.0
```

### Relevant log output

```shell
Error Output:
Error: internalError: "failed to bootstrap container" (cause: "internalError: "failed to bootstrap container redis (cause: "invalidState: "container expected to be in created state, got: shuttingDown"")"")

Container System Logs (container system logs):

container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] starting start [uuid=redis]
2025-11-03 15:07:16.912561+0530 0x3495b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] configuring XPC server [uuid=redis]
2025-11-03 15:07:16.912799+0530 0x3495b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] starting XPC server [uuid=redis]
2025-11-03 15:07:16.913228+0530 0x3496a    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `createEndpoint` xpc handler [uuid=redis]
2025-11-03 15:07:16.913521+0530 0x3496a    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `bootstrap` xpc handler [uuid=redis]
2025-11-03 15:07:16.917368+0530 0x3496c    Info        0x0                  7903   0    container-network-vmnet: [com.apple.container:NetworkVmnetHelper] allocated attachment [address=192.168.64.19/24] [gateway=192.168.64.1] [hostname=redis] [id=default]
2025-11-03 15:07:16.917587+0530 0x3495b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] creating NATNetworkInterface with network reference [uuid=redis]
2025-11-03 15:07:17.358438+0530 0x3495b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `startProcess` xpc handler [uuid=redis]
2025-11-03 15:07:17.466438+0530 0x3469e    Info        0x0                  7894   0    container-apiserver: [com.apple.container:APIServer] registering container redis with exit monitor
2025-11-03 15:07:17.466587+0530 0x3495b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `state` xpc handler [uuid=redis]
2025-11-03 15:07:17.467322+0530 0x3496b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `wait` xpc handler [uuid=redis]
2025-11-03 15:07:19.197011+0530 0x3496a    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `stop` xpc handler [uuid=redis]
2025-11-03 15:07:19.311404+0530 0x3496a    Error       0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] process deletion [id=redis] [uuid=redis] [error=internal error (13): unknown error processing request]
2025-11-03 15:07:19.318388+0530 0x3495b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] init process exited with: ExitStatus(exitCode: 0, exitedAt: 2025-11-03 09:37:19 +0000) [uuid=redis]
2025-11-03 15:07:19.392325+0530 0x349e8    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] closing forwarders [uuid=redis]
2025-11-03 15:07:19.392326+0530 0x349e8    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] closed forwarders [uuid=redis]
2025-11-03 15:07:19.392639+0530 0x34750    Info        0x0                  7903   0    container-network-vmnet: [com.apple.container:NetworkVmnetHelper] released attachments [id=default] [hostname=redis]
2025-11-03 15:07:19.397007+0530 0x345fa    Info        0x0                  7894   0    container-apiserver: [com.apple.container:APIServer] Shutting down sandbox service for redis
2025-11-03 15:07:19.397250+0530 0x3496b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `shutdown` xpc handler [uuid=redis]
2025-11-03 15:07:20.820642+0530 0x349e8    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `createEndpoint` xpc handler [uuid=redis]
2025-11-03 15:07:20.821021+0530 0x3496b    Info        0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] `bootstrap` xpc handler [uuid=redis]
2025-11-03 15:07:20.821794+0530 0x3496b    Error       0x0                  20755  0    container-runtime-linux: [com.apple.container:RuntimeLinuxHelper] handler for com.apple.container.sandbox/bootstrap threw error invalidState: "container expected to be in created state, got: shuttingDown" [uuid=redis]
2025-11-03 15:07:20.831084+0530 0x3469e    Error       0x0                  7894   0    container-apiserver: [com.apple.container:APIServer] WaitHandler for redis threw error internalError: "failed to wait for process redis in container redis" (cause: "interrupted: "XPC connection error: Connection interrupted"")
2025-11-03 15:07:20.903142+0530 0x346a0    Error       0x0                  7894   0    container-apiserver: [com.apple.container:APIServer] handler for containerBootstrap threw error internalError: "failed to bootstrap container redis" (cause: "invalidState: "container expected to be in created state, got: shuttingDown"")
2025-11-03 15:07:20.903147+0530 0x3469f    Info        0x0                  7894   0    container-apiserver: [com.apple.container:APIServer] Handling container redis exit. Code ExitStatus(exitCode: -1, exitedAt: 2025-11-03 09:37:20 +0000)
2025-11-03 15:07:20.903712+0530 0x3469e    Error       0x0                  7894   0    container-apiserver: [com.apple.container:APIServer] handler for containerStop threw error notFound: "container with ID redis not found"
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by realrajaryan**
- Fixes #833.

## Type of Change
- [x] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Motivation and Context
Currently, when stopping and immediately restarting a container, it would fail with the error:
`“container expected to be in created state, got: shuttingDown”` and then be automatically deleted.
The `SandboxService` process waits five seconds before exiting after shutdown. During this interval, a rapid restart could reconnect to the still-terminating process in the `shuttingDown` state, triggering a state validation error.

This fix forcefully terminates the `SandboxService` process with `SIGKILL` upon container exit, instead of waiting five seconds. The bootstrap now defensively checks for and cleans up any stale services before registering new ones, preventing reconnections to processes in the `shuttingDown` state.

## Testing
- [x] Tested locally
- [ ] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

**Comment by dcantah** [comment]
I think we should just get rid of the 5 second sleep+exit and deregister (and not ignore the error) in stop. The shutdown rpc is just meant as a way (our docs here are shitty, otherwise it'd be easier to tell 😄) for any implementations of the sandbox service to clean up any resources it may have created during container lifecycle (temp files, sockets, whatever). I think we can just rely on the APIServer to kill it, and not have the sandbox service itself exit on its own. I'm not sure on that entirely, but it seems fine to me to leave having it exit up to the APIServer.

So:

1. Remove the `Task` sleep and exit  in shutdown rpc.
2. Always deregister after shutdown comes back successfully.
3. Get rid of the checks you added in bootstrap

**Comment by realrajaryan** [comment]
> I think we should just get rid of the 5 second sleep+exit and deregister (and not ignore the error) in stop. The shutdown rpc is just meant as a way (our docs here are shitty, otherwise it'd be easier to tell 😄) for any implementations of the sandbox service to clean up any resources it may have created during container lifecycle (temp files, sockets, whatever). I think we can just rely on the APIServer to kill it, and not have the sandbox service itself exit on its own. I'm not sure on that entirely, but it seems fine to me to leave having it exit up to the APIServer.
> 
> So:
> 
> 1. Remove the `Task` sleep and exit  in shutdown rpc.
> 2. Always deregister after shutdown comes back successfully.
> 3. Get rid of the checks you added in bootstrap

I’m also gonna move service registration from create() to bootstrap(), because if create() registers the service and bootstrap() registers again it’ll fail. This way services start when containers are actually running.

File: Sources/Services/ContainerAPIService/Containers/ContainersService.swift [hunk 1]
```diff
@@ -457,15 +450,23 @@ public actor ContainersService {
...
+        let path = self.containerRoot.appendingPathComponent(id)
+        let bundle = ContainerClient.Bundle(path: path)
+        let config = try bundle.configuration
+        let label = Self.fullLaunchdServiceLabel(
+            runtimeName: config.runtimeHandler,
+            instanceId: id
+        )
+
+        let client = try state.getClient()
+        try await client.shutdown()
```
Comment (dcantah) [inline Sources/Services/ContainerAPIService/Containers/ContainersService.swift:465]: Sorry, I still think shutdown shouldn't be fatal and we can leave what we had as it's mostly best effort cleanup on the sb services end, I just meant to not ignore all of the errors like what you had in your original change.

Comment (dcantah) [reply Sources/Services/ContainerAPIService/Containers/ContainersService.swift:465]: We're in a weird spot if deregistration fails though. Curious on your thoughts on how to handle that.

Comment (realrajaryan) [reply Sources/Services/ContainerAPIService/Containers/ContainersService.swift:465]: ahh, If deregister fails, we could catch it and attempt kill SIGKILL + deregister as a fallback?

File: Sources/Services/ContainerAPIService/Containers/ContainersService.swift [hunk 2]
```diff
@@ -90,19 +90,12 @@ public actor ContainersService {
                     )
                 )
                 results[config.id] = state
-                let plugin = runtimePlugins.first { $0.name == config.runtimeHandler }
-                guard let plugin else {
+                guard runtimePlugins.first(where: { $0.name == config.runtimeHandler }) != nil else {
```
Comment (jglogan) [inline Sources/Services/ContainerAPIService/Containers/ContainersService.swift:93]: nit: more concise here and on L155:

```swift
guard runtimePlugins.contains(where: { $0.name == config.runtimeHandler }) else {
...
}
```

File: Sources/Services/ContainerSandboxService/SandboxService.swift [hunk 3]
```diff
@@ -272,15 +272,6 @@ public actor SandboxService {
             case .created, .stopped(_), .stopping:
                 await self.setState(.shuttingDown)
 
-                Task {
```
Comment (jglogan) [inline Sources/Services/ContainerSandboxService/SandboxService.swift:275]: Is it that containers won't ever stop gracefully anymore?

To ensure containers and attached volumes preserve written data don't we want something like:

- Send SIGTERM to the primary workload and additional processes (execs)
- Wait a certain amount of time for the processes to complete and be reaped and then vminitd terminates normally and the VM shuts down of its own accord
- If this doesn't happen within a certain time shut down the VM forcefully

This isn't unlike what launchd does for macOS services

Comment (dcantah) [reply Sources/Services/ContainerSandboxService/SandboxService.swift:275]: Truthfully we should ensure the container (singular as that's all we support currently, but can be expanded to whatever the N is) is dead in shutdown. If the sandbox svc is still servicing any containers we should return an error. Shutdown should solely be a final little handshake to cleanup some possible resources before getting killed.

Comment (jglogan) [reply Sources/Services/ContainerSandboxService/SandboxService.swift:275]: > If the sandbox svc is still servicing any containers we should return an error.

We should return an error for what? That the container cannot be stopped?

What should the UX be for `stop`, given that properly stopping a container (or pod) can be a somewhat slow operation?

How best do we handle cases where a container (or pod) workload processes don't shut down in a timely manner?

If `container stop c1 c2 c3 c4` signals these four containers to shut down, do we want to return immediately after telling them, or wait until we know that all are in the stopped state? The former is more responsive but can produce the condition that prompted this issue.

Comment (dcantah) [reply Sources/Services/ContainerSandboxService/SandboxService.swift:275]: > We should return an error for what? That the container cannot be stopped?

No, if there are still containers running in the handler for `shutdown` on any given sandbox svc we should throw an error. I/we should probably spend a week documenting the behaviors of the various rpcs so folks know what we expect the behavior is for every call, but I was modeling `shutdown` much after containerd's. It's meant as a final place to do any resource cleanup (possibly none like in our case, but depends on the implementation) after we've gone through the rounds already and stopped (or they may have exited on their own) any containers.

**Comment by pd95** [comment]
@realrajaryan: I have successfully tested this branch/fork. Thanks for this!

@dcantah: Could we please merge this PR into main? Or are there still changes needed?

**Review by dcantah — APPROVED** [review]
Lets fix the follow ups later. This needs to be resolved
