### PR TITLE
Fix broken image integration tests.

### LINKED ISSUE #943: [Bug]: TestCLIImages current download tests break other image tests.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

The test for concurrent downloads removes the `ghcr.io/linuxcontainers/alpine:3.20` in between pulls with different concurrency values.

This will cause other image tests to randomly fail as they are also trying to work with this image.

### Current behavior

Image tests fail nondeterministically.

### Expected behavior

Image tests pass.

### Environment

```markdown
- OS: macOS 26
- Xcode: 26
- Container: 0.7.1
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jglogan**
- Fixes #943.
- Use images other than alpine:3.20 for image concurrency test so as not to interfere with tests using that image.
- Rename test files to match suite names.

## Type of Change
- [x] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Motivation and Context
Fixes #943.

## Testing
- [x] Tested locally
- [x] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

File: Tests/CLITests/Subcommands/Run/TestCLIRunCommand.swift [hunk 1]
```diff
@@ -513,20 +513,22 @@ class TestCLIRunCommand: CLITest {
...
-            #expect(success, "Request to \(url) failed after \(retries - retriesRemaining) retries")
+            try #require(success, "Request to \(url) failed after \(retries - retriesRemaining) retries")
             try doStop(name: name)
         } catch {
             Issue.record("failed to run container \(error)")
             return
         }
     }
 
+    /*
```
Comment (katiewasnothere) [inline Tests/CLITests/Subcommands/Run/TestCLIRunCommand.swift]: Did you mean to comment this test out?

File: Tests/CLITests/Subcommands/Images/TestCLIImages.swift [hunk 2]
```diff
@@ -378,16 +378,13 @@ extension TestCLIImagesCommand {
...
         do {
-            try doPull(imageName: alpine, args: ["--max-concurrent-downloads", "1"])
-            let imagePresent = try isImagePresent(targetImage: alpine)
+            try doPull(imageName: alpine_concurrency1, args: ["--max-concurrent-downloads", "1"])
+            let imagePresent = try isImagePresent(targetImage: alpine_concurrency1)
             #expect(imagePresent, "Expected image to be pulled with maxConcurrentDownloads=1")
 
-            // Clean up
-            try? doRemoveImages(images: [alpine])
-
```
Comment (katiewasnothere) [inline Tests/CLITests/Subcommands/Images/TestCLIImages.swift:387]: We're no longer guaranteeing that either of these images are not already pulled locally. And as it is right now, this test is not really validating that the value is respected, just that the command doesn't fail. If this test just cares about if the command can accept valid "max-concurrent-downloads" values, we can just try to pull the normal alpine image. 

We should probably add some unit tests at a different level. What do you think?

Comment (jglogan) [reply Tests/CLITests/Subcommands/Images/TestCLIImages.swift:387]: In CI, the are guaranteed to be pulled locally in this test as long as nobody pulls those same images (which is why I used the symbols I did).

**Review by katiewasnothere — APPROVED** [review]

**Comment by saehejkang** [comment]
Looks like this solves the issues that I am getting when writing tests for `image prune` 💯
