### PR TITLE
Fix progress bar crash on cached image rebuilds

### LINKED ISSUE #883: [Bug]: Image download progress bar breaks rebuilds.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

Build an image with a simple Dockerfile (`FROM docker.io/library/alpine:latest` should reproduce it).

Perform the same build command.

### Current behavior

```console
% container build -t test -f Dockerfile .
Warning! Running debug build. Performance may be degraded.
[+] Building 3.0s (4/4) FINISHED                                                                                                                                                                                                \

 => [resolver] fetching image...some.path/to/image:some-tag                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                           0.1s
 => => transferring context: 2B                                                                                                                                                                                             0.0s
 => CACHED oci-layout://some.path/to/image:some-tag@sha256:53bd5d1c57734504eea2ba6ea0d36fd09289d6e6613d6a3be47774cd481542c6                                                               0.1s
 => => resolve some.path/to/image:some-tag@sha256:53bd5d1c57734504eea2ba6ea0d36fd09289d6e6613d6a3be47774cd481542c6                                                                        0.1s
 => exporting to oci image format                                                                                                                                                                                           1.6s
 => => exporting layers                                                                                                                                                                                                     0.0s
 => => exporting manifest sha256:3d3c5775804c50a9653a44e0963db8e31844245f49153ff352975c7c7d4e5aeb                                                                                                                           0.0s
 => => exporting config sha256:30e8d18c07d108a319d0bc9c1a9a37f520ae33b3b88b2bcdcdf7a0ce33850cd1                                                                                                                             0.0s
 => => exporting manifest list sha256:92d3a4402310b650fa4ca27a4984a790ae03c7212ff8e4cc996c7ff85237709c                                                                                                                      0.0s
 => => sending tarball                                                                                                                                                                                                      1.5s
Successfully built test:latest
/Users/john/Documents/sandboxes/20251117-vessel-buildcaching % container build -t test -f Dockerfile .
Warning! Running debug build. Performance may be degraded.
[+] Building 0.0s (0/1)                                                                                                                                                                                                         \

 => [resolver] fetching image...some.path/to/image:some-tag                                                                                                                               0.0s
Swift/StringLegacy.swift:31: Fatal error: Negative count not allowede 100% |█| (1/1 KB, 2 KB/s) [0s]
Swift/StringLegacy.swift:31: Fatal error: Negative count not allowede 100% |█| (1/1 KB, 2 KB/s) [0s]
Swift/StringLegacy.swift:31: Fatal error: Negative count not allowede 100% |█| (1/1 KB, 2 KB/s) [0s]
Swift/StringLegacy.swift:31: Fatal error: Negative count not allowede 100% |█| (1/1 KB, 2 KB/s) [0s]
Swift/StringLegacy.swift:31: Fatal error: Negative count not allowed
Swift/StringLegacy.swift:31: Fatal error: Negative count not allowede 100% |█| (1/1 KB, 2 KB/s) [0s]
zsh: trace trap  container build -t test -f Dockerfile .r:3.4.7-apple 29% |  | (74.2/252.1 MB, 2 KB/s) [0s]
```

### Expected behavior

The rebuild should succeed, with no error messages in the output.

### Environment

```markdown
- OS: 26.1
- Xcode: 26
- Container: main
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by realrajaryan**
- Fixes #883.

Changes `BuildImageResolver` to use `fetch()` instead of `pull()`. 

`fetch()` checks the cache first and only pulls if needed, preventing  incorrect progress events (e.g., "1/1 KB" metadata checks) on cached images that caused the progress bar width calculation to produce negative/weird padding counts, triggering "Fatal error: Negative count not allowed" crashes during rebuilds.

### CODE REVIEW

File: Sources/ContainerBuild/BuildImageResolver.swift [hunk 1]
```diff
@@ -72,10 +72,8 @@ struct BuildImageResolver: BuildPipelineHandler {
             defer { progress.finish() }
             progress.start()
 
-            guard let img = try? await ClientImage.pull(reference: ref, platform: platform, progressUpdate: progress.handler) else {
-                return try await ClientImage.fetch(reference: ref, platform: platform, progressUpdate: progress.handler)
-            }
-            return img
+            // Use fetch() which checks cache first, then pulls if needed
+            return try await ClientImage.fetch(reference: ref, platform: platform, progressUpdate: progress.handler)
```
Comment (jglogan) [inline Sources/ContainerBuild/BuildImageResolver.swift:76]: `fetch()` only retrieves the manifest if needed, doesn't it?

I don't see how this actually pulls content. The code before the original progress bar changed looked like:

```swift
           guard let img = try? await ClientImage.pull(reference: ref, platform: platform) else {
                return try await ClientImage.fetch(reference: ref, platform: platform)
```

Comment (realrajaryan) [reply Sources/ContainerBuild/BuildImageResolver.swift:76]: The original code was backwards. [`fetch()`](https://github.com/apple/container/blob/87b5623ecdbdb1dfdf0c33735030ae2a5499417e/Sources/ContainerClient/Core/ClientImage.swift#L296) tries to get the image from the local cache first, and if not found, it calls pull().

**Review by jglogan — APPROVED** [review]
