### PR TITLE
Propagate host ssh socket permissions to relay socket in guest.

### LINKED ISSUE #580: [Bug]: `--ssh` flag doesn't work with non-root user
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

Dockerfile:

```dockerfile
FROM alpine:latest
RUN addgroup -S nonroot \
&&  adduser -S -G nonroot -h /home/nonroot nonroot \
&&  apk add openssh-client git
USER nonroot
WORKDIR /home/nonroot
```

### Current behavior

```console
% container run -it --rm --ssh test sh   
Warning! Running debug build. Performance may be degraded.
~ $ git clone git@github.com:apple/containerization.git
Cloning into 'containerization'...
The authenticity of host 'github.com (140.82.112.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~ $ ls -l ${SSH_AUTH_SOCK}
s---------    1 root     root             0 Sep  5 14:57 /run/host-services/ssh-auth.sock
```

### Expected behavior

`git clone` should work.

### Environment

```markdown
- OS: 26 beta
- Xcode: 26 beta
- Container: 0.4.1
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jglogan**
- Closes #580.
- Depends on apple/containerization#362.

## Type of Change
- [x] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Testing
- [x] Tested locally
- [ ] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

File: Sources/Services/ContainerSandboxService/SandboxService.swift [hunk 1]
```diff
@@ -793,11 +794,16 @@ public actor SandboxService {
             czConfig.sockets.append(socketConfig)
         }
 
-        if let socketUrl = Self.hostSocketUrl(config: config) {
+        if let socketUrl = Self.sshAuthSocketHostUrl(config: config) {
+            let socketPath = socketUrl.path(percentEncoded: false)
+            let attrs = try FileManager.default.attributesOfItem(atPath: socketPath)
```
Comment (realrajaryan) [inline Sources/Services/ContainerSandboxService/SandboxService.swift]: do we wanna handle the scenario when `attributesOfItem` throws?

Comment (jglogan) [reply Sources/Services/ContainerSandboxService/SandboxService.swift]: ah yeah, let's default to what we were doing before for that case as well

**Review by realrajaryan — APPROVED** [review]
