### PR TITLE
Send tar hash in the first BuildTransfer packet

### LINKED ISSUE #1143: [Bug]: buildkit container loose sync when tgz archive
### I have done the following

- [x] I have searched the existing issues
- [ ] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

1. `container stop buildkit; container rm buildkit`.
2. `cd Tools; ./run.sh`.
3. edit `Dockerfile.sh`, change "Hello World" to "Hello World 2".
4. `./run.sh`.

After the second run, instead of "Hello World 2" output you'll get "Hello World". This is because fssync breaks in `buildkit` container. It never updates files anymore. I tried different archives but can't reproduce it nowhere except the one attached.

Interestingly, my superpower is finding bugs, and this is literally the first docker image I've ever built on Apple Containers, and it took me a whole day to figure out the cause and create this bug report.

It's fun that I can't upload archive here, "Failed to upload". So here is a link to Google Driver: https://drive.google.com/file/d/1AzUpGAiK2UETB6YaWnt-TbbpN9V3hee9/view?usp=share_link

### Current behavior

Does not sync filesystem inside `buildkit` container.

### Expected behavior

Should work flawlessly like Podman and Docker.

### Environment

```markdown
- OS: Tahoe 26.2
- Xcode: N/A
- Container: 0.8.0
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JaewonHur**
Send the hash of entire tar file in the first BuildTransfer packet to prevent container-builder-shim from using stale cached contents.

This PR resolves #1143.
This PR relies on apple/container-builder-shim#64.

## Type of Change
- [X] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Motivation and Context
Current container-builder-shim uses only first few bytes of tar file as checksum, which leads to the usage of stale cached contents if the change of build context is not included in the first bytes of tar file.

## Testing
- [X] Tested locally
- [ ] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

File: Sources/ContainerBuild/BuildFSSync.swift [hunk 1]
```diff
@@ -229,6 +230,27 @@ actor BuildFSSync: BuildPipelineHandler {
                 pathInArchive: URL(fileURLWithPath: rel))
         }
 
+        let tarData = try Data(contentsOf: tarURL)
```
Comment (realrajaryan) [inline Sources/ContainerBuild/BuildFSSync.swift]: The hash could be computed during compression (`Archiver.compress()`) above instead of reading the entire tar back into memory which could be an issue for large build contexts

Comment (JaewonHur) [reply Sources/ContainerBuild/BuildFSSync.swift]: Agree. Moved hash computation to compress logic.

Comment (jglogan) [reply Sources/ContainerBuild/BuildFSSync.swift]: @JaewonHur review the PR @Ronitsabhaya75 submitted three hours before and see if it will suffice. Thanks!

**Comment by Ronitsabhaya75** [comment]
@jglogan I was looking at @JaewonHur approaches and mine

**PR #1149 (Jae's approach - tar hash):**

Pros:  Hashes actual tar content after creation, catches any tar-level changes (format, compression)
Cons:  Requires changes to both repos (container + container-builder-shim), Could be more complex deployment

**PR #1145 (My approach - metadata hash):**
Pros:   Self-contained fix in container repo only, simpler to deploy and maintain
Conss:   Hashes metadata not content, may miss edge cases where files change but metadata doesn't


Both solve 1143, but different cache invalidation strategies.


let me know what are the suggestion of yours here.

**Comment by realrajaryan** [comment]
> @jglogan I was looking at @JaewonHur approaches and mine
> 
> **PR #1149 (Jae's approach - tar hash):**
> 
> Pros: Hashes actual tar content after creation, catches any tar-level changes (format, compression) Cons: Requires changes to both repos (container + container-builder-shim), Could be more complex deployment
> 
> **PR #1145 (My approach - metadata hash):** Pros: Self-contained fix in container repo only, simpler to deploy and maintain Conss: Hashes metadata not content, may miss edge cases where files change but metadata doesn't
> 
> Both solve 1143, but different cache invalidation strategies.
> 
> let me know what are the suggestion of yours here.

Hey @Ronitsabhaya75, thank you for contributing to container.

Changes across both repos are not a concern if they lead to a more robust solution. Deployments for `container-builder-shim` are handled via GitHub Actions, and the follow-up in `container` is just a version bump.

One piece of feedback for next time: it would be better to discuss the approach and design in the issue thread first, so we can align early before implementation.

Also, please take a look at our [AI contribution guidelines](https://github.com/apple/containerization/blob/main/CONTRIBUTING.md#ai-contribution-guidelines) when you get a chance :)

**Comment by Ronitsabhaya75** [comment]
> > @jglogan I was looking at @JaewonHur approaches and mine
> > **PR #1149 (Jae's approach - tar hash):**
> > Pros: Hashes actual tar content after creation, catches any tar-level changes (format, compression) Cons: Requires changes to both repos (container + container-builder-shim), Could be more complex deployment
> > **PR #1145 (My approach - metadata hash):** Pros: Self-contained fix in container repo only, simpler to deploy and maintain Conss: Hashes metadata not content, may miss edge cases where files change but metadata doesn't
> > Both solve 1143, but different cache invalidation strategies.
> > let me know what are the suggestion of yours here.
> 
> Hey @Ronitsabhaya75, thank you for contributing to container.
> 
> Changes across both repos are not a concern if they lead to a more robust solution. Deployments for `container-builder-shim` are handled via GitHub Actions, and the follow-up in `container` is just a version bump.
> 
> One piece of feedback for next time: it would be better to discuss the approach and design in the issue thread first, so we can align early before implementation.
> 
> Also, please take a look at our [AI contribution guidelines](https://github.com/apple/containerization/blob/main/CONTRIBUTING.md#ai-contribution-guidelines) when you get a chance :)

Thanks for the feedback! I've reviewed the AI contribution guidelines and understand the importance of discussing design approaches in the issue first. sorry for mistake :(

- thanks for the guidance!

**Comment by JaewonHur** [comment]
Hi @Ronitsabhaya75,
Sorry for the duplicate PR. I missed one while working on my side.

Thank you for the contribution!
I added co-author!

**Comment by Ronitsabhaya75** [comment]
@JaewonHur My apologies :(. I should have discussed the approach in the issue before implementing it. 

After reviewing your solution, I agree that hashing the actual tar content is the more robust approach. 

It catches all changes including tar format variations, which my metadata-only hash would have miss.

**Comment by jglogan** [comment]
> sorry for mistake

Not a mistake, really. We all (myself included) could communicate more through the issues before putting PRs up here.

Thanks for putting in the effort and for working things out!

**Review by jglogan — APPROVED** [review]
