### PR TITLE
Fix directory watcher

### LINKED ISSUE #1207: [Bug]: Directory monitor for localhost DNS fails if no resolver directory.
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

In CI, many runners don't have an /etc/resolver directory set up, which causes the local DNS task to fail on API server start.

This results in an error during the test phase of the git action; the`install-kernel` make target fails on `container system start`.

The directory monitor must transition between two operational states:

- when the directory is not present, remove all localhost DNS entries, and poll until the directory is present
- when the directory is present, process any localhost DNS files and then monitor for changes

### Current behavior

tests crash on CI while installing kernel

### Expected behavior

tests run as expected

### Environment

```markdown
- OS: 26
- Xcode: 26
- Container: 0.9.0.2
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JaewonHur**
Current DirectoryWatcher fails if `/etc/resolver` does not exist. This PR fixes DirectoryWatcher to handle non-existing `/etc/resolver` directory. If that directory does not exist, it first watches `/etc` directory to check if `/etc/resolver` directory is created later. Once it detects new `/etc/resolver` directory, it starts watching new DNS resolver files there.

This PR also fixes to log the exception thrown by API server's tasks.

Resolves #1207

## Type of Change
- [X] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Motivation and Context
In case of non-existing `/etc/resolver` starting API server fails.

## Testing
- [X] Tested locally
- [ ] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

File: Sources/ContainerOS/DirectoryWatcher.swift [hunk 1]
```diff
@@ -15,46 +15,48 @@
 //===----------------------------------------------------------------------===//
 
 import ContainerizationError
+import ContainerizationOS
```
Comment (jglogan) [inline Sources/ContainerOS/DirectoryWatcher.swift:18]: I don't think this should go in DNSServer.

Right now LocalDNSHandler depends on ContainerAPIClient and ContainerDNSHandler holds a reference on networksService and thus depends on ContainerAPIService.

Is it possible to rework ContainerDNSHandler so that it doesn't use an injected dependency and instead uses the API client like LocalDNSHandler does?

Then we the dependencies simplified, we could create a `Sources/Services/ContainerAPIService/Library` or something like it and move this and the DNS handlers into it.

File: Sources/DNSServer/DirectoryWatcher.swift [hunk 2]
```diff
@@ -15,46 +15,48 @@
 //===----------------------------------------------------------------------===//
 
 import ContainerizationError
+import ContainerizationOS
 import Foundation
 import Logging
 
 public class DirectoryWatcher {
```
Comment (jglogan) [inline Sources/DNSServer/DirectoryWatcher.swift]: add docc for class and methods

File: Sources/DNSServer/DirectoryWatcher.swift [hunk 3]
```diff
@@ -66,19 +68,64 @@ public class DirectoryWatcher {
...
 
-    deinit {
-        guard let source else {
+    public func startWatching(handler: @escaping ([URL]) throws -> Void) throws {
+        guard source == nil else {
+            throw ContainerizationError(.invalidState, message: "already watching on \(directoryURL.path)")
+        }
+
+        let parent = directoryURL.deletingLastPathComponent().resolvingSymlinksInPathWithPrivate()
+        guard parent.isDirectory else {
```
Comment (jglogan) [inline Sources/DNSServer/DirectoryWatcher.swift]: We should document this function to mention that it only works if the parent directory exists.

What would the tradeoff be if we just polled for the presence of the parent directory? Some extra latency when going from polling to watching, but can watch anything under any condition.

Comment (JaewonHur) [reply Sources/DNSServer/DirectoryWatcher.swift]: Moved to use polling based approach.

File: Sources/ContainerOS/DirectoryWatcher.swift (hunk 1 above)
Comment (JaewonHur) [reply Sources/ContainerOS/DirectoryWatcher.swift:18]: Added `Sources/ContainerOS` for low level stuffs and moved `DirectoryWatcher.swift` under it.

File: Sources/Helpers/APIServer/LocalhostDNSHandler.swift [hunk 4]
```diff
@@ -15,18 +15,19 @@
...
 import Foundation
 import Logging
 
-class LocalhostDNSHandler: DNSHandler {
+actor LocalhostDNSHandler: DNSHandler {
     private let ttl: UInt32
     private let watcher: DirectoryWatcher
 
-    private var dns: [String: IPv4]
+    nonisolated(unsafe) private var dns: [String: IPv4]
```
Comment (jglogan) [inline Sources/Helpers/APIServer/LocalhostDNSHandler.swift]: `nonisolated(unsafe)` says that the type is protected against concurrent access some other way? Is that the case here?

Comment (JaewonHur) [reply Sources/Helpers/APIServer/LocalhostDNSHandler.swift]: Updated to use mutex. Thanks!
